---
baseURL: 'https://www.anshulgoyal.in'
relativeURLs: true
canonifyurls: true
enableRobotsTXT: true
languageCode: en-us
metaDataFormat: yaml
pygmentsCodeFences: true
pygmentsStyle: emacs

author: Anshul Goyal
title: Anshul Goyal
theme: goa

blackfriday:
  hrefTargetBlank: true

params:
  intro: Anshul Goyal
  description: Kuch krke dikhana hai.. :D :p
  authorimage: authorImage.jpg
  enableRSS: true
  dateFormat: 'Jan 2, 2006'
  extra:
    copyright: '&copy; 2017. Anshul Goyal.'
    poweredBy: true
  social:
    linkedin: anshulgoyal81
    facebook: anshulgoyal81
    email: anshul.goyal.81@gmail.com
  menu:
    main:
      - name: ""
        url: /files/Resume.pdf
        weight: 1
